name: Get & Cache Dependencies
description: Get the dependencies (via npm) and cache them.

inputs:
  caching:
    description: Whether to cache dependencies or not.
    required: false
    default: 'true'

outputs:
  used-cache:
    description: Whether the cache was used.
    value: ${{ steps.set-output.outputs.used-cache }}

runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: inputs.caching != 'true' || steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Set output
      id: set-output
      run: |
        if [ "${{ inputs.caching }}" != "true" ]; then
          echo "used-cache=false" >> $GITHUB_OUTPUT
        else
          echo "used-cache=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
